"use client";

import React, { useState, useMemo } from "react";
import { 
  FileCode2, 
  Copy, 
  CheckCircle2, 
  Download, 
  Plus, 
  Trash2, 
  ShieldCheck,
  Globe
} from "lucide-react";
import { cn } from "@/lib/utils";

export default function RobotsTxtGenerator() {
  const [userAgent, setUserAgent] = useState("*");
  const [disallowPaths, setDisallowPaths] = useState<string[]>([
    "/admin/",
    "/api/",
    "/private/",
    "/*.json$"
  ]);
  const [allowPaths, setAllowPaths] = useState<string[]>([
    "/public/",
    "/api/og"
  ]);
  const [sitemapUrl, setSitemapUrl] = useState("https://yourdomain.com/sitemap.xml");
  const [newDisallow, setNewDisallow] = useState("");
  const [newAllow, setNewAllow] = useState("");
  const [copied, setCopied] = useState(false);

  const robotsContent = useMemo(() => {
    let output = `# robots.txt generated by Exismic AI Studio\n`;
    output += `User-agent: ${userAgent}\n`;

    disallowPaths.forEach((path) => {
      if (path.trim()) output += `Disallow: ${path.trim()}\n`;
    });

    allowPaths.forEach((path) => {
      if (path.trim()) output += `Allow: ${path.trim()}\n`;
    });

    if (sitemapUrl.trim()) {
      output += `\nSitemap: ${sitemapUrl.trim()}\n`;
    }

    return output;
  }, [userAgent, disallowPaths, allowPaths, sitemapUrl]);

  const addDisallow = () => {
    if (!newDisallow.trim()) return;
    setDisallowPaths([...disallowPaths, newDisallow.trim()]);
    setNewDisallow("");
  };

  const addAllow = () => {
    if (!newAllow.trim()) return;
    setAllowPaths([...allowPaths, newAllow.trim()]);
    setNewAllow("");
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(robotsContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([robotsContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "robots.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="mx-auto max-w-5xl space-y-8 p-4 sm:p-6 lg:p-8">
      {/* Banner */}
      <div className="relative overflow-hidden rounded-3xl border border-cyan-500/20 bg-gradient-to-br from-cyan-950/40 via-zinc-950 to-black p-6 sm:p-8 backdrop-blur-xl shadow-2xl">
        <div className="absolute -top-24 -right-24 h-64 w-64 rounded-full bg-cyan-500/10 blur-3xl pointer-events-none" />
        <div className="relative z-10 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
          <div className="space-y-2 max-w-2xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 text-xs font-black uppercase tracking-wider">
              <FileCode2 size={14} className="text-cyan-400" />
              <span>Webmaster Utility</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-black text-white uppercase tracking-tight">
              Robots.txt Generator
            </h1>
            <p className="text-zinc-400 text-sm font-medium leading-relaxed">
              Visual robots.txt builder with User-Agent rules, Disallow paths, and Sitemap integration.
            </p>
          </div>
        </div>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Rules Form */}
        <div className="space-y-6 rounded-3xl border border-white/10 bg-white/[0.02] p-6 backdrop-blur-md">
          <div className="space-y-2">
            <label className="text-xs font-black uppercase tracking-wider text-zinc-300">
              User-Agent Bot Target
            </label>
            <input
              type="text"
              value={userAgent}
              onChange={(e) => setUserAgent(e.target.value)}
              placeholder="e.g. * or Googlebot"
              className="w-full rounded-xl border border-white/10 bg-black/50 px-4 py-3 text-sm text-zinc-200 focus:border-cyan-500 focus:outline-none"
            />
          </div>

          <div className="space-y-2">
            <label className="text-xs font-black uppercase tracking-wider text-zinc-300">
              Disallow Paths (Block Crawling)
            </label>
            <div className="flex gap-2">
              <input
                type="text"
                value={newDisallow}
                onChange={(e) => setNewDisallow(e.target.value)}
                placeholder="/path-to-block/"
                className="flex-1 rounded-xl border border-white/10 bg-black/50 px-4 py-2.5 text-xs text-zinc-200 focus:border-cyan-500 focus:outline-none"
              />
              <button
                type="button"
                onClick={addDisallow}
                className="px-4 py-2.5 rounded-xl bg-cyan-500/20 hover:bg-cyan-500/30 text-cyan-300 text-xs font-bold uppercase tracking-wider border border-cyan-500/40 cursor-pointer"
              >
                Add
              </button>
            </div>
            <div className="flex flex-wrap gap-1.5 pt-2">
              {disallowPaths.map((p, i) => (
                <span key={i} className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-red-500/10 border border-red-500/30 text-red-300 text-xs font-mono">
                  {p}
                  <button type="button" onClick={() => setDisallowPaths(disallowPaths.filter((_, idx) => idx !== i))} className="hover:text-white cursor-pointer">×</button>
                </span>
              ))}
            </div>
          </div>

          <div className="space-y-2">
            <label className="text-xs font-black uppercase tracking-wider text-zinc-300">
              Sitemap Directive URL
            </label>
            <input
              type="text"
              value={sitemapUrl}
              onChange={(e) => setSitemapUrl(e.target.value)}
              placeholder="https://yourdomain.com/sitemap.xml"
              className="w-full rounded-xl border border-white/10 bg-black/50 px-4 py-3 text-sm text-zinc-200 focus:border-cyan-500 focus:outline-none"
            />
          </div>
        </div>

        {/* Generated Output */}
        <div className="space-y-4 rounded-3xl border border-white/10 bg-white/[0.02] p-6 backdrop-blur-md flex flex-col justify-between">
          <label className="text-xs font-black uppercase tracking-wider text-zinc-300 flex items-center gap-2">
            <FileCode2 size={15} className="text-cyan-400" />
            Generated robots.txt File
          </label>

          <pre className="w-full flex-1 min-h-[260px] rounded-2xl border border-white/10 bg-black/80 p-4 text-xs font-mono text-cyan-300 overflow-y-auto leading-relaxed">
            {robotsContent}
          </pre>

          <div className="flex gap-3">
            <button
              type="button"
              onClick={handleCopy}
              className="flex-1 py-3.5 rounded-xl bg-white/10 hover:bg-white/15 border border-white/15 text-white text-xs font-bold uppercase tracking-wider transition-all flex items-center justify-center gap-2 cursor-pointer"
            >
              {copied ? <CheckCircle2 size={16} className="text-emerald-400" /> : <Copy size={16} />}
              <span>{copied ? "Copied!" : "Copy Code"}</span>
            </button>
            <button
              type="button"
              onClick={handleDownload}
              className="flex-1 py-3.5 rounded-xl bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white text-xs font-bold uppercase tracking-wider transition-all flex items-center justify-center gap-2 shadow-lg cursor-pointer"
            >
              <Download size={16} />
              <span>Download file</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
