import AiDetector from "@/components/tool/AiDetector";
import { ToolPageShell } from "@/components/tool/ToolPageShell";
import { constructMetadata, SITE_URL } from "@/lib/seo";

export const metadata = constructMetadata({
  title: "Free AI Content Detector - Scan Text for ChatGPT & AI Writing | Exismic",
  description: "Check if text was generated by AI models like ChatGPT or Claude. Get sentence-by-sentence analysis and human confidence scores.",
  canonicalUrl: `${SITE_URL}/tools/ai-detector`,
  keywords: ["AI detector", "ChatGPT detector", "AI content checker", "free AI text scanner", "Claude detector"],
});

export default function Page() {
  return (
    <ToolPageShell
      toolId="ai-detector"
      categoryId="ai"
      customTitle="AI Content Detector"
      customDescription="Scan text to identify AI-generated patterns from ChatGPT, Claude, and Gemini with sentence-level highlights."
    >
      <AiDetector />
    </ToolPageShell>
  );
}
