import AiDetector from "@/components/tool/AiDetector";
import { constructMetadata, SITE_URL } from "@/lib/seo";
import { ToolSeoSection } from "@/components/seo/ToolSeoSection";

export const metadata = constructMetadata({
  title: "Free AI Content Detector - Scan Text for ChatGPT & AI Writing | Exismic",
  description: "Accurately check if text was generated by AI models like ChatGPT, GPT-4, or Claude. Get sentence-by-sentence analysis and confidence scores.",
  canonicalUrl: `${SITE_URL}/tools/ai-detector`,
  keywords: ["AI detector", "ChatGPT detector", "AI content checker", "free AI text scanner", "Claude detector"],
});

export default function Page() {
  return (
    <>
      <AiDetector />
      <ToolSeoSection
        toolName="AI Content Detector"
        toolDescription="Accurately check if text was generated by AI models like ChatGPT, GPT-4, or Claude. Get sentence-by-sentence analysis and confidence scores."
        categoryName="AI Tools"
        categoryId="ai"
        toolSlug="/tools/ai-detector"
      />
    </>
  );
}

