import AiDetector from "@/components/tool/AiDetector";

export const metadata = {
  title: "Free AI Content Detector - Scan Text for ChatGPT & AI Writing | Exismic",
  description: "Accurately check if text was generated by AI models like ChatGPT, GPT-4, or Claude. Get sentence-by-sentence analysis and confidence scores.",
};

export default function Page() {
  return <AiDetector />;
}
