CREATE TABLE IF NOT EXISTS public.auth_rate_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  type TEXT NOT NULL,
  last_requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT auth_rate_limits_email_type_key UNIQUE (email, type),
  CONSTRAINT auth_rate_limits_type_check CHECK (type IN ('otp_verification', 'magic_link', 'password_reset'))
);

CREATE INDEX IF NOT EXISTS auth_rate_limits_email_type_idx
ON public.auth_rate_limits (email, type);
