"use client";

import React, { useState, useMemo } from "react";
import { FileCode, Copy, Check, Sparkles, RefreshCw, Zap } from "lucide-react";
import { cn } from "@/lib/utils";

export default function SvgOptimizer() {
  const [rawSvg, setRawSvg] = useState(
    `<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100" xml:space="preserve" xmlns:serif="http://www.serif.com/">\n  <!-- Generated by Figma / Illustrator -->\n  <g id="Layer_1">\n    <circle cx="50" cy="50" r="40" fill="#a3e635" stroke="#15803d" stroke-width="4"/>\n  </g>\n</svg>`
  );
  const [stripComments, setStripComments] = useState(true);
  const [stripDimensions, setStripDimensions] = useState(true);
  const [stripMetadata, setStripMetadata] = useState(true);
  const [copied, setCopied] = useState(false);

  const optimizedSvg = useMemo(() => {
    let svg = rawSvg.trim();
    if (!svg) return "";

    if (stripComments) {
      svg = svg.replace(/<!--[\s\S]*?-->/g, "");
    }
    if (stripMetadata) {
      svg = svg.replace(/xmlns:serif="[^"]*"/g, "");
      svg = svg.replace(/xml:space="[^"]*"/g, "");
      svg = svg.replace(/id="[^"]*"/g, "");
    }
    if (stripDimensions) {
      svg = svg.replace(/\s(width|height)="[^"]*"/g, "");
    }
    // Minify whitespace
    svg = svg.replace(/>\s+</g, "><").replace(/\s{2,}/g, " ").trim();
    return svg;
  }, [rawSvg, stripComments, stripDimensions, stripMetadata]);

  const rawBytes = new Blob([rawSvg]).size;
  const optBytes = new Blob([optimizedSvg]).size;
  const savingsPct = rawBytes > 0 ? Math.max(0, Math.round(((rawBytes - optBytes) / rawBytes) * 100)) : 0;

  const handleCopy = () => {
    navigator.clipboard.writeText(optimizedSvg);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full max-w-5xl mx-auto space-y-8">
      {/* Banner */}
      <div className="p-6 sm:p-8 rounded-3xl bg-gradient-to-br from-lime-950/40 via-emerald-900/20 to-neutral-900 border border-lime-500/20 shadow-2xl backdrop-blur-xl space-y-3">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-lime-500/10 border border-lime-500/30 text-lime-300 text-xs font-semibold uppercase tracking-wider">
          <FileCode className="w-3.5 h-3.5" /> SVG Compression Engine
        </div>
        <h2 className="text-2xl sm:text-4xl font-extrabold text-white tracking-tight">
          SVG Optimizer & File Cleaner (SVGO)
        </h2>
        <p className="text-neutral-400 text-sm sm:text-base max-w-2xl">
          Strip unnecessary XML metadata, Figma/Illustrator junk, and redundant inline attributes to compress SVG payload size by 40-70%.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Input Column */}
        <div className="lg:col-span-6 space-y-4 p-6 rounded-3xl bg-neutral-900/80 border border-neutral-800 backdrop-blur-xl shadow-xl">
          <label className="block text-xs font-bold text-neutral-300 uppercase tracking-wider mb-1">
            Raw SVG Markup
          </label>
          <textarea
            value={rawSvg}
            onChange={(e) => setRawSvg(e.target.value)}
            rows={8}
            className="w-full p-4 rounded-2xl bg-neutral-950 border border-neutral-800 text-lime-300 text-xs font-mono focus:outline-none focus:border-lime-500 leading-relaxed resize-none"
          />

          <div className="space-y-2 pt-2 border-t border-neutral-800">
            <span className="text-xs font-bold text-neutral-400 uppercase tracking-wider block mb-1">
              Optimization Rules
            </span>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs text-neutral-300">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={stripComments}
                  onChange={(e) => setStripComments(e.target.checked)}
                  className="rounded bg-neutral-950 border-neutral-800 text-lime-500 focus:ring-lime-500"
                />
                Remove HTML/XML Comments
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={stripDimensions}
                  onChange={(e) => setStripDimensions(e.target.checked)}
                  className="rounded bg-neutral-950 border-neutral-800 text-lime-500 focus:ring-lime-500"
                />
                Strip fixed `width` / `height`
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={stripMetadata}
                  onChange={(e) => setStripMetadata(e.target.checked)}
                  className="rounded bg-neutral-950 border-neutral-800 text-lime-500 focus:ring-lime-500"
                />
                Strip Editor Namespaces & IDs
              </label>
            </div>
          </div>
        </div>

        {/* Output Column */}
        <div className="lg:col-span-6 space-y-4 flex flex-col justify-between">
          <div className="p-6 rounded-3xl bg-neutral-900/80 border border-neutral-800 backdrop-blur-xl shadow-xl flex-1 flex flex-col justify-between">
            <div className="flex items-center justify-between border-b border-neutral-800 pb-3 mb-4">
              <div className="flex items-center gap-3">
                <span className="text-xs font-bold text-lime-400 uppercase tracking-wider">
                  Optimized SVG
                </span>
                <span className="text-xs font-bold text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded-full border border-emerald-500/30">
                  {savingsPct}% Saved ({rawBytes}B → {optBytes}B)
                </span>
              </div>
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-lime-600 hover:bg-lime-500 text-white text-xs font-bold transition-all shadow-lg shadow-lime-600/30"
              >
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? "Copied SVG!" : "Copy SVG"}
              </button>
            </div>

            <pre className="p-4 sm:p-5 rounded-2xl bg-neutral-950 border border-neutral-800 text-lime-300 font-mono text-xs overflow-x-auto whitespace-pre-wrap leading-relaxed shadow-inner my-auto max-h-[220px]">
              {optimizedSvg}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
