export type CosmeticRarity = "Rare" | "Epic" | "Legendary";
export type RotationTier = "daily" | "three_day" | "weekly" | "permanent";

export interface SparksShopItem {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  costSparks: number;
  category: "cosmetic" | "perks" | "vouchers" | "credits" | "pro";
  type: "streak_shield" | "shop_voucher" | "credits_emergency" | "credits_bonus" | "credits_permanent" | "pro_pass" | "avatar_frame" | "name_gradient" | "creator_insignia" | "studio_canopy" | "free_sparks";
  value: number | string; // credits amount, pro pass hours, or cosmetic id
  badge?: string;
  popular?: boolean;
  accentColor: "amber" | "cyan" | "purple" | "emerald" | "fuchsia" | "rose" | "red" | "blue" | "silver";
  rarity: "Starter" | "Rare" | "Epic" | "Legendary" | "Mythic";
  rotationTier: RotationTier;
}

// 7-day limited-time gift event ends September 14, 2026 23:59:59 UTC
export const FREE_SPARKS_GIFT_EXPIRES_AT = new Date("2026-09-14T23:59:59.999Z");

export const FREE_SPARKS_GIFT_ITEM: SparksShopItem = {
  id: "sparks_free_gift_100",
  title: "100 Free Sparks",
  subtitle: "Special Community Gift",
  description: "A free gift for every creator! Claim your 100 free Sparks to pick up avatar frames, glowing names, or streak shields in the shop.",
  costSparks: 0,
  category: "perks",
  type: "free_sparks",
  value: 100,
  badge: "Free Gift",
  popular: true,
  accentColor: "amber",
  rarity: "Legendary",
  rotationTier: "permanent",
};

// ==========================================
// 1. PERMANENT STAPLES (STREAK SHIELDS, VOUCHERS & EMERGENCY PERKS)
// ==========================================
export const PERMANENT_SHOP_ITEMS: SparksShopItem[] = [
  FREE_SPARKS_GIFT_ITEM,
  {
    id: "sparks_streak_freeze_1x",
    title: "Streak Freeze (1x Shield)",
    subtitle: "Streak Protection",
    description: "Saves your daily streak if you miss logging in for one day. Automatically consumed if you miss a day. Stacks up to 3 shields.",
    costSparks: 250,
    category: "perks",
    type: "streak_shield",
    value: 1,
    badge: "Streak Saver",
    popular: true,
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "permanent",
  },
  {
    id: "sparks_streak_guardian_3x",
    title: "Streak Guardian (3x Bundle)",
    subtitle: "Max Shield Capacity",
    description: "Instantly tops up your streak vault to the maximum capacity of 3 active streak shields for complete peace of mind.",
    costSparks: 600,
    category: "perks",
    type: "streak_shield",
    value: 3,
    badge: "Best Protection",
    popular: true,
    accentColor: "amber",
    rarity: "Epic",
    rotationTier: "permanent",
  },
  {
    id: "sparks_shop_voucher_100",
    title: "Shop Discount Voucher",
    subtitle: "Real-Money Shop Coupon",
    description: "Generates a single-use coupon code valid for ₹100 or $1.50 off purchases of ₹249 / $3.00 or more in the Shop.",
    costSparks: 400,
    category: "vouchers",
    type: "shop_voucher",
    value: 100,
    badge: "Shop Coupon",
    accentColor: "purple",
    rarity: "Rare",
    rotationTier: "permanent",
  },
  {
    id: "sparks_shop_voucher_20pct",
    title: "20% OFF Monthly Pro Pass",
    subtitle: "VIP Monthly Pro Discount",
    description: "Generates a single-use 20% discount coupon code valid on 1-Month Exismic Pro memberships. Does not stack on Yearly Pro.",
    costSparks: 850,
    category: "vouchers",
    type: "shop_voucher",
    value: 20,
    badge: "VIP Discount",
    accentColor: "fuchsia",
    rarity: "Epic",
    rotationTier: "permanent",
  },
  {
    id: "sparks_emergency_refuel_25",
    title: "Emergency Refuel (25 Credits)",
    subtitle: "Quick 24-Hour Compute",
    description: "Emergency trickle of 25 temporary credits to complete your active creation when daily credits deplete. Expires in 24 hours.",
    costSparks: 350,
    category: "perks",
    type: "credits_emergency",
    value: 25,
    badge: "Emergency Only",
    accentColor: "emerald",
    rarity: "Starter",
    rotationTier: "permanent",
  },
];

// ==========================================
// 2. AVATAR FRAMES MASTER POOL (RANKED BY RARITY)
// ==========================================

// RARE FRAMES (Daily Rotation — Resets every 24h at 00:00 UTC)
export const RARE_AVATAR_FRAMES: SparksShopItem[] = [
  {
    id: "frame_neon_glow",
    title: "Neon Cyber Glow",
    subtitle: "Cyberpunk Cyan Halo",
    description: "Electrifies your avatar with an animated rotating cyan-to-purple neon glow edge.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "neon-glow",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "frame_cyan_beast",
    title: "Liquid Cyan Glow",
    subtitle: "Cyan Aqua Surge",
    description: "High-contrast dynamic aqua border flowing with emerald energy pulses.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "cyan-beast",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "frame_futuristic_hex",
    title: "Futuristic Hex Grid",
    subtitle: "High-Tech Carbon Mesh",
    description: "Precision hexagonal cyber weave rotating around your creator avatar.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "futuristic-hex",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "frame_emerald_viper",
    title: "Emerald Toxic Matrix",
    subtitle: "Biohazard Acid Glow",
    description: "Vibrant neon lime and emerald particle halo radiating around your profile.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "emerald-viper",
    badge: "Daily Drop",
    accentColor: "emerald",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "frame_diamond_ice",
    title: "Glacier Diamond Frost",
    subtitle: "Sub-Zero Crystal Shards",
    description: "Sharp crystalline diamond facets reflecting arctic blue starlight.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "diamond-ice",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "frame_purple_energy",
    title: "Void Purple Spark",
    subtitle: "Subtle Astral Energy",
    description: "Swirling deep purple void glow illuminating your creator presence.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "purple-energy",
    badge: "Daily Drop",
    accentColor: "purple",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "frame_hyper_violet",
    title: "Hyper Violet Singularity",
    subtitle: "Deep Space Gravity Well",
    description: "Intense rotating violet starlight with energetic atmospheric rim light.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "hyper-violet",
    badge: "Daily Drop",
    accentColor: "purple",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "frame_astral_void",
    title: "Astral Void Singularity",
    subtitle: "Gravitational Light Lens",
    description: "Deep interstellar violet with rotating cyan stardust particles and gravitational flare.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "astral-void",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "frame_molten_dragon",
    title: "Molten Dragon Core",
    subtitle: "Primal Magma Ring",
    description: "Seething magma gold and fiery crimson bursts forged in dragon fire.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "molten-dragon",
    badge: "Daily Drop",
    accentColor: "red",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "frame_cyber_glitch",
    title: "Cyber Matrix Glitch",
    subtitle: "High-Frequency Scanline",
    description: "Phosphor green and hyper-pink digital scanline matrix pulse.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "cyber-glitch",
    badge: "Daily Drop",
    accentColor: "emerald",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "frame_frostfire_eclipse",
    title: "Frostfire Celestial",
    subtitle: "Dual-Element Corona",
    description: "Subzero diamond glacier ice balanced against roaring solar prominences.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "frostfire-eclipse",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "frame_chrono_warp",
    title: "Chrono Temporal Flux",
    subtitle: "Relativistic Time Ring",
    description: "Clockwork bronze temporal gears with cyan relativistic light distortion.",
    costSparks: 300,
    category: "cosmetic",
    type: "avatar_frame",
    value: "chrono-warp",
    badge: "Daily Drop",
    accentColor: "amber",
    rarity: "Rare",
    rotationTier: "daily",
  },
];

// EPIC FRAMES (3-Day Rotation — Resets every 3 days at 00:00 UTC)
export const EPIC_AVATAR_FRAMES: SparksShopItem[] = [
  {
    id: "frame_cyberpunk_vibe",
    title: "Cyber Grid Circuit",
    subtitle: "Neon Glitch Border",
    description: "Futuristic neon red-orange racing border with high-velocity light rotation.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "cyberpunk-vibe",
    badge: "3-Day Vault",
    popular: true,
    accentColor: "amber",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_cosmic_nebula",
    title: "Cosmic Nebula Dust",
    subtitle: "Stellar Starlight Swirl",
    description: "Deep violet and galactic starlight particle swirl wrapping your avatar.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "cosmic-nebula",
    badge: "3-Day Vault",
    accentColor: "purple",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_royal_purple",
    title: "Royal Purple Glow",
    subtitle: "Majestic Amethyst Aura",
    description: "Rich royal violet and amethyst light ribbons crafted for distinguished creators.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "royal-purple",
    badge: "3-Day Vault",
    accentColor: "purple",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_solar_flare",
    title: "Solar Flare Supernova",
    subtitle: "Molten Solar Prominence",
    description: "Explosive amber and solar crimson flares pulsing with cosmic heat.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "solar-flare",
    badge: "3-Day Vault",
    accentColor: "amber",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_aurora_borealis",
    title: "Aurora Northern Lights",
    subtitle: "Chromatic Polar Wave",
    description: "Ethereal emerald, teal, and magenta aurora borealis curtain undulating smoothly.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "aurora-borealis",
    badge: "3-Day Vault",
    popular: true,
    accentColor: "emerald",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_hologram_prism",
    title: "Holographic Prism Matrix",
    subtitle: "Iridescent Light Refraction",
    description: "Full-spectrum chromatic refraction with dynamic rainbow light shifts.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "hologram-prism",
    badge: "3-Day Vault",
    accentColor: "cyan",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_crimson_inferno",
    title: "Crimson Blood Inferno",
    subtitle: "Blazing Hellfire Reactor",
    description: "Fierce molten ruby and volcanic ember glow with high-intensity edge sheen.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "crimson-inferno",
    badge: "3-Day Vault",
    accentColor: "amber",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_sakura_blossom",
    title: "Sakura Cyber Blossom",
    subtitle: "Digital Cherry Petals",
    description: "Delicate neon rose petals and soft magenta glow with spring cherry aesthetics.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "sakura-blossom",
    badge: "3-Day Vault",
    accentColor: "fuchsia",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_void_walker",
    title: "Voidwalker Eclipse",
    subtitle: "Ultraviolet Event Horizon",
    description: "Deep obsidian onyx with pulsing ultraviolet event horizon flares.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "void-walker",
    badge: "3-Day Vault",
    accentColor: "purple",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_synthwave_80s",
    title: "Retro Synthwave Grid",
    subtitle: "Neon Sunset Horizon",
    description: "80s Miami vice hot fuchsia and electric sunset orange retro wireframe aesthetic.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "synthwave-80s",
    badge: "3-Day Vault",
    accentColor: "rose",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_jade_dynasty",
    title: "Imperial Jade Sovereign",
    subtitle: "Radiant Imperial Relic",
    description: "Imperial jade gemstone edge interlaced with polished bullion gold.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "jade-dynasty",
    badge: "3-Day Vault",
    accentColor: "emerald",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_blood_moon",
    title: "Blood Moon Eclipse",
    subtitle: "Haunting Lunar Halo",
    description: "Eerie deep scarlet halo with smoke noir shadows and blood prominence pulses.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "blood-moon",
    badge: "3-Day Vault",
    accentColor: "red",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "frame_quantum_maglev",
    title: "Quantum Superconductor",
    subtitle: "Levitating Cobalt Surge",
    description: "Blazing cobalt blue and levitating superconductor neon cyan ring.",
    costSparks: 500,
    category: "cosmetic",
    type: "avatar_frame",
    value: "quantum-maglev",
    badge: "3-Day Vault",
    accentColor: "blue",
    rarity: "Epic",
    rotationTier: "three_day",
  },
];

// LEGENDARY FRAMES (Weekly Rotation — Resets every Monday at 00:00 UTC)
export const LEGENDARY_AVATAR_FRAMES: SparksShopItem[] = [
  {
    id: "frame_obsidian_onyx",
    title: "Obsidian Stealth Onyx",
    subtitle: "Volcanic Shimmer Edge",
    description: "Ultra-luxurious dark obsidian frame with specular golden rim reflections.",
    costSparks: 800,
    category: "cosmetic",
    type: "avatar_frame",
    value: "obsidian-onyx",
    badge: "Weekly Vault",
    popular: true,
    accentColor: "amber",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "frame_luxury_gold",
    title: "Luxury Gold Status",
    subtitle: "Solid 24K Radiant Gold",
    description: "Pure metallic gold luster with brilliant specular glints for top creators.",
    costSparks: 800,
    category: "cosmetic",
    type: "avatar_frame",
    value: "luxury-gold",
    badge: "Weekly Vault",
    popular: true,
    accentColor: "amber",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "frame_quantum_flux",
    title: "Quantum Flux Reactor",
    subtitle: "High-Energy Plasma Core",
    description: "Quad-color hyper-accelerated quantum ring radiating intense cyan & emerald energy.",
    costSparks: 800,
    category: "cosmetic",
    type: "avatar_frame",
    value: "quantum-flux",
    badge: "Weekly Vault",
    accentColor: "cyan",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "frame_celestial_platinum",
    title: "Celestial Royal Platinum",
    subtitle: "Specular Diamond Platinum",
    description: "Rare silver-white platinum sheen with diamond-like crystal clarity.",
    costSparks: 800,
    category: "cosmetic",
    type: "avatar_frame",
    value: "celestial-platinum",
    badge: "Weekly Vault",
    accentColor: "silver",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "frame_plasma_storm",
    title: "Electric Plasma Storm",
    subtitle: "High-Voltage Arc Discharge",
    description: "Rapid rotating yellow and cyan lightning arcs with crackling thunder visuals.",
    costSparks: 800,
    category: "cosmetic",
    type: "avatar_frame",
    value: "plasma-storm",
    badge: "Weekly Vault",
    accentColor: "amber",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "frame_golden_pharaoh",
    title: "Mythic Sun Pharaoh",
    subtitle: "Ancient Sun God Majesty",
    description: "Warm desert gold with amber sun-disk halo reflecting timeless authority.",
    costSparks: 800,
    category: "cosmetic",
    type: "avatar_frame",
    value: "golden-pharaoh",
    badge: "Weekly Vault",
    accentColor: "amber",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "frame_dark_matter",
    title: "Abyssal Dark Matter",
    subtitle: "Event Horizon Void Rim",
    description: "Deep cosmic obsidian and midnight purple with eerie cyan boundary glow.",
    costSparks: 800,
    category: "cosmetic",
    type: "avatar_frame",
    value: "dark-matter",
    badge: "Weekly Vault",
    accentColor: "purple",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "frame_starlight_valkyrie",
    title: "Starlight Valkyrie",
    subtitle: "Divine Rose-Gold Halo",
    description: "Pearlescent white titanium, divine rose-gold, and iridescent celestial aura.",
    costSparks: 850,
    category: "cosmetic",
    type: "avatar_frame",
    value: "starlight-valkyrie",
    badge: "Weekly Vault",
    accentColor: "fuchsia",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "frame_toxic_biohazard",
    title: "Biohazard Radioactive",
    subtitle: "Uranium Warning Core",
    description: "Warning sign uranium lime with toxic hazard flashing amber and glowing emerald mist.",
    costSparks: 850,
    category: "cosmetic",
    type: "avatar_frame",
    value: "toxic-biohazard",
    badge: "Weekly Vault",
    accentColor: "emerald",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "frame_phantom_wraith",
    title: "Ethereal Phantom Mist",
    subtitle: "Spectral Lavender Drift",
    description: "Spectral translucent lavender vapor and ghostly sea-cyan drift from beyond.",
    costSparks: 850,
    category: "cosmetic",
    type: "avatar_frame",
    value: "phantom-wraith",
    badge: "Weekly Vault",
    accentColor: "purple",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "frame_solaris_apex",
    title: "Solaris Apex Corona",
    subtitle: "Thermonuclear Prominence",
    description: "Blinding white-gold thermonuclear coronal loops with radiant prominence beams.",
    costSparks: 850,
    category: "cosmetic",
    type: "avatar_frame",
    value: "solaris-apex",
    badge: "Weekly Vault",
    accentColor: "amber",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "frame_abyssal_kraken",
    title: "Abyssal Trench Biolume",
    subtitle: "Trench Leviathan Light",
    description: "Mariana Trench midnight navy with vivid neon turquoise jellyfish luminescence.",
    costSparks: 850,
    category: "cosmetic",
    type: "avatar_frame",
    value: "abyssal-kraken",
    badge: "Weekly Vault",
    accentColor: "cyan",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
];

// ==========================================
// 3. NAME STYLES MASTER POOL (RANKED BY RARITY)
// ==========================================

// RARE NAME STYLES (Daily Rotation — Resets every 24h at 00:00 UTC)
export const RARE_NAME_STYLES: SparksShopItem[] = [
  {
    id: "gradient_cyber_purple",
    title: "Cyber Purple",
    subtitle: "Electric Violet Username",
    description: "Applies a radiant high-contrast purple-to-fuchsia flowing gradient to your display name.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "cyber-purple",
    badge: "Daily Drop",
    accentColor: "purple",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "gradient_neon_emerald",
    title: "Neon Emerald",
    subtitle: "Radioactive Matrix Glow",
    description: "Crisp toxic green text with cyan edge shimmer cutting through dark mode.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "neon-emerald",
    badge: "Daily Drop",
    accentColor: "emerald",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "gradient_void_blue",
    title: "Void Blue",
    subtitle: "Deep Oceanic Trench",
    description: "Subtle deep sapphire-to-indigo current bringing quiet authority to your name.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "void-blue",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "gradient_sunset_flame",
    title: "Sunset Flame",
    subtitle: "Molten Solar Flare",
    description: "Dynamic fiery orange-to-amber text style illuminating your name across community views.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "sunset-flame",
    badge: "Daily Drop",
    popular: true,
    accentColor: "amber",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "gradient_diamond_glacier",
    title: "Diamond Glacier",
    subtitle: "Frostbite Crystal Blue",
    description: "Pale icy cyan with high-reflectance diamond glint accents.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "diamond-glacier",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "gradient_emerald_matrix",
    title: "Emerald Matrix",
    subtitle: "Terminal Cyber Code",
    description: "Electric lime and teal flowing text inspired by legendary hacker consoles.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "emerald-matrix",
    badge: "Daily Drop",
    accentColor: "emerald",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "gradient_electric_amber",
    title: "Electric Amber",
    subtitle: "Dynamic Spark Glow",
    description: "Warm electric gold with lightning-fast horizontal shimmer highlights.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "electric-amber",
    badge: "Daily Drop",
    accentColor: "amber",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "gradient_astral_void",
    title: "Astral Void Singularity",
    subtitle: "Starlight Violet Cyan",
    description: "Flowing cosmic violet with shimmering celestial cyan highlights.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "astral-void",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "gradient_molten_dragon",
    title: "Molten Dragon Flame",
    subtitle: "Primal Lava Fire",
    description: "Roaring crimson to searing molten gold flame gradient.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "molten-dragon",
    badge: "Daily Drop",
    accentColor: "red",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "gradient_cyber_glitch",
    title: "Cyber Matrix Glitch",
    subtitle: "Digital Scanline Flow",
    description: "Emerald green and electric pink digital glitch cyber text.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "cyber-glitch",
    badge: "Daily Drop",
    accentColor: "emerald",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "gradient_frostfire_eclipse",
    title: "Frostfire Celestial",
    subtitle: "Ice & Fire Blend",
    description: "Diamond glacier ice fading into blazing sunset orange flame.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "frostfire-eclipse",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "gradient_chrono_warp",
    title: "Chrono Temporal Flux",
    subtitle: "Bronze Clockwork Light",
    description: "Temporal antique gold into light-bending chrono cyan.",
    costSparks: 250,
    category: "cosmetic",
    type: "name_gradient",
    value: "chrono-warp",
    badge: "Daily Drop",
    accentColor: "amber",
    rarity: "Rare",
    rotationTier: "daily",
  },
];

// EPIC NAME STYLES (3-Day Rotation — Resets every 3 days at 00:00 UTC)
export const EPIC_NAME_STYLES: SparksShopItem[] = [
  {
    id: "gradient_royal_crimson",
    title: "Royal Crimson",
    subtitle: "Blood Ruby Radiance",
    description: "Intense deep red and imperial purple gradient radiating confident power.",
    costSparks: 400,
    category: "cosmetic",
    type: "name_gradient",
    value: "royal-crimson",
    badge: "3-Day Vault",
    accentColor: "amber",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "gradient_hyper_fuchsia",
    title: "Hyper Fuchsia",
    subtitle: "Vaporwave Pink Surge",
    description: "Ultra-bright magenta and bubblegum pink flowing gradient with high contrast.",
    costSparks: 400,
    category: "cosmetic",
    type: "name_gradient",
    value: "hyper-fuchsia",
    badge: "3-Day Vault",
    accentColor: "fuchsia",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "gradient_stealth_silver",
    title: "Stealth Silver Platinum",
    subtitle: "Liquid Mirror Metal",
    description: "Refined chrome and pure white reflections with clean executive aesthetic.",
    costSparks: 400,
    category: "cosmetic",
    type: "name_gradient",
    value: "stealth-silver",
    badge: "3-Day Vault",
    accentColor: "silver",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "gradient_hologram_prism",
    title: "Holographic Prism",
    subtitle: "Full-Spectrum Light Wave",
    description: "Multidimensional holographic shimmer that shifts colors smoothly across your name.",
    costSparks: 400,
    category: "cosmetic",
    type: "name_gradient",
    value: "hologram-prism",
    badge: "3-Day Vault",
    popular: true,
    accentColor: "cyan",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "gradient_crimson_inferno",
    title: "Crimson Inferno",
    subtitle: "Molten Lava Text Flare",
    description: "Deep magma red with blazing orange core lighting up your username.",
    costSparks: 400,
    category: "cosmetic",
    type: "name_gradient",
    value: "crimson-inferno",
    badge: "3-Day Vault",
    accentColor: "amber",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "gradient_quantum_mint",
    title: "Quantum Mint Flux",
    subtitle: "Bioluminescent Mint Glow",
    description: "Neon cyan and cool mint green flowing wave bringing fresh energy to your ID.",
    costSparks: 400,
    category: "cosmetic",
    type: "name_gradient",
    value: "quantum-mint",
    badge: "3-Day Vault",
    accentColor: "emerald",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "gradient_sakura_bloom",
    title: "Sakura Cyber Bloom",
    subtitle: "Luminescent Floral Gradient",
    description: "Warm pastel rose with vivid fuchsia accents inspired by Tokyo cherry blossom nights.",
    costSparks: 400,
    category: "cosmetic",
    type: "name_gradient",
    value: "sakura-bloom",
    badge: "3-Day Vault",
    accentColor: "fuchsia",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "gradient_void_walker",
    title: "Voidwalker Eclipse",
    subtitle: "Pulsing Ultraviolet Core",
    description: "Deep obsidian violet with pulsing event horizon ultraviolet sheen.",
    costSparks: 450,
    category: "cosmetic",
    type: "name_gradient",
    value: "void-walker",
    badge: "3-Day Vault",
    accentColor: "purple",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "gradient_synthwave_80s",
    title: "Retro Synthwave Sunset",
    subtitle: "Miami Sunset Fuchsia",
    description: "Hot magenta and warm sunset orange flowing retro synthwave text.",
    costSparks: 450,
    category: "cosmetic",
    type: "name_gradient",
    value: "synthwave-80s",
    badge: "3-Day Vault",
    accentColor: "rose",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "gradient_jade_dynasty",
    title: "Imperial Jade Sovereign",
    subtitle: "Imperial Relic Jade",
    description: "Imperial emerald green marbled with brilliant sovereign bullion gold.",
    costSparks: 450,
    category: "cosmetic",
    type: "name_gradient",
    value: "jade-dynasty",
    badge: "3-Day Vault",
    accentColor: "emerald",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "gradient_blood_moon",
    title: "Blood Moon Eclipse",
    subtitle: "Lunar Crimson Pulse",
    description: "Haunting scarlet and deep velvet blood red with radiant eclipse drop shadow.",
    costSparks: 450,
    category: "cosmetic",
    type: "name_gradient",
    value: "blood-moon",
    badge: "3-Day Vault",
    accentColor: "red",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "gradient_quantum_maglev",
    title: "Quantum Superconductor",
    subtitle: "Cobalt Electric Cyan",
    description: "Liquid superconductor neon cyan with magnetic cobalt blue pulses.",
    costSparks: 450,
    category: "cosmetic",
    type: "name_gradient",
    value: "quantum-maglev",
    badge: "3-Day Vault",
    accentColor: "blue",
    rarity: "Epic",
    rotationTier: "three_day",
  },
];

// LEGENDARY NAME STYLES (Weekly Rotation — Resets every Monday at 00:00 UTC)
export const LEGENDARY_NAME_STYLES: SparksShopItem[] = [
  {
    id: "gradient_cosmic_rainbow",
    title: "Cosmic Rainbow",
    subtitle: "Prismatic Chromatic Wave",
    description: "Multicolor iridescent holographic glow making your identity instantly unmistakable.",
    costSparks: 650,
    category: "cosmetic",
    type: "name_gradient",
    value: "cosmic-rainbow",
    badge: "Weekly Vault",
    popular: true,
    accentColor: "fuchsia",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "gradient_luxury_gold",
    title: "Luxury Gold",
    subtitle: "24K Burnished Gold Luster",
    description: "Sleek liquid gold lettering with warm amber shadows and brilliant center highlights.",
    costSparks: 650,
    category: "cosmetic",
    type: "name_gradient",
    value: "luxury-gold",
    badge: "Weekly Vault",
    popular: true,
    accentColor: "amber",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "gradient_solar_supernova",
    title: "Solar Supernova",
    subtitle: "Pure Golden Prestige",
    description: "Intense radiant 24K gold flare style reserved for Exismic's most dedicated creators.",
    costSparks: 650,
    category: "cosmetic",
    type: "name_gradient",
    value: "solar-supernova",
    badge: "Weekly Vault",
    popular: true,
    accentColor: "amber",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "gradient_aurora_borealis",
    title: "Northern Aurora",
    subtitle: "Dancing Starlight Ribbons",
    description: "Magnificent emerald, teal, and violet starlight ribbon gradient across your name.",
    costSparks: 650,
    category: "cosmetic",
    type: "name_gradient",
    value: "aurora-borealis",
    badge: "Weekly Vault",
    accentColor: "emerald",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "gradient_plasma_neon",
    title: "Electric Plasma",
    subtitle: "Dual Arc Neon Discharge",
    description: "High-voltage yellow-to-cyan plasma stream with dynamic crackling luminescence.",
    costSparks: 650,
    category: "cosmetic",
    type: "name_gradient",
    value: "plasma-neon",
    badge: "Weekly Vault",
    accentColor: "cyan",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "gradient_mythic_pharaoh",
    title: "Mythic Sun Pharaoh",
    subtitle: "Sacred Imperial Gold Text",
    description: "Ancient Egyptian sun god gold with intense amber drop-shadow glow.",
    costSparks: 650,
    category: "cosmetic",
    type: "name_gradient",
    value: "mythic-pharaoh",
    badge: "Weekly Vault",
    accentColor: "amber",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "gradient_abyssal_violet",
    title: "Abyssal Ultra Violet",
    subtitle: "Deep Stellar Singularity",
    description: "Deep violet starlight and indigo nebula dust with hypnotic radiant text glow.",
    costSparks: 650,
    category: "cosmetic",
    type: "name_gradient",
    value: "abyssal-violet",
    badge: "Weekly Vault",
    accentColor: "purple",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "gradient_starlight_valkyrie",
    title: "Starlight Valkyrie",
    subtitle: "Divine Pearlescent Glow",
    description: "Divine pearlescent white, rose-gold, and celestial lavender aura.",
    costSparks: 750,
    category: "cosmetic",
    type: "name_gradient",
    value: "starlight-valkyrie",
    badge: "Weekly Vault",
    accentColor: "fuchsia",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "gradient_toxic_biohazard",
    title: "Biohazard Radioactive",
    subtitle: "Uranium Neon Glow",
    description: "Radioactive neon lime into hazard yellow and toxic teal glowing text.",
    costSparks: 750,
    category: "cosmetic",
    type: "name_gradient",
    value: "toxic-biohazard",
    badge: "Weekly Vault",
    accentColor: "emerald",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "gradient_phantom_wraith",
    title: "Ethereal Phantom Mist",
    subtitle: "Spectral Lavender Drift",
    description: "Translucent spectral lavender and ghostly ethereal mist drop shadow.",
    costSparks: 750,
    category: "cosmetic",
    type: "name_gradient",
    value: "phantom-wraith",
    badge: "Weekly Vault",
    accentColor: "purple",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "gradient_solaris_apex",
    title: "Solaris Apex Corona",
    subtitle: "Blinding White-Gold Flare",
    description: "Blinding white-gold thermonuclear flare with radiant corona prominence text.",
    costSparks: 750,
    category: "cosmetic",
    type: "name_gradient",
    value: "solaris-apex",
    badge: "Weekly Vault",
    accentColor: "amber",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "gradient_abyssal_kraken",
    title: "Abyssal Trench Biolume",
    subtitle: "Bioluminescent Cyan Azure",
    description: "Mariana trench navy with electric bioluminescent jellyfish turquoise luminescence.",
    costSparks: 750,
    category: "cosmetic",
    type: "name_gradient",
    value: "abyssal-kraken",
    badge: "Weekly Vault",
    accentColor: "cyan",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
];

// ==========================================
// 4. CREATOR INSIGNIAS (TITLE CRESTS)
// ==========================================
export const RARE_CREATOR_INSIGNIAS: SparksShopItem[] = [
  {
    id: "insignia_bolt_spark",
    title: "Overcharged Spark",
    subtitle: "Kinetic Voltage Crest",
    description: "High-voltage kinetic spark core with electric crackle.",
    costSparks: 250,
    category: "cosmetic",
    type: "creator_insignia",
    value: "bolt-spark",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "insignia_matrix_cube",
    title: "Matrix Core",
    subtitle: "Encrypted Data Nexus",
    description: "Cyber cubic nexus pulsing with synchronized sub-nodes.",
    costSparks: 250,
    category: "cosmetic",
    type: "creator_insignia",
    value: "matrix-cube",
    badge: "Daily Drop",
    accentColor: "emerald",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "insignia_emerald_prism",
    title: "Emerald Prism",
    subtitle: "Bio-Synthetic Crystal",
    description: "Bio-synthetic prism radiating pure photosynthetic energy.",
    costSparks: 250,
    category: "cosmetic",
    type: "creator_insignia",
    value: "emerald-prism",
    badge: "Daily Drop",
    accentColor: "emerald",
    rarity: "Rare",
    rotationTier: "daily",
  },
  {
    id: "insignia_ice_shard",
    title: "Glacier Shard",
    subtitle: "Sub-Zero Refraction",
    description: "Cold-forged crystalline diamond shard with sub-zero prism light.",
    costSparks: 250,
    category: "cosmetic",
    type: "creator_insignia",
    value: "ice-shard",
    badge: "Daily Drop",
    accentColor: "cyan",
    rarity: "Rare",
    rotationTier: "daily",
  },
];

export const EPIC_CREATOR_INSIGNIAS: SparksShopItem[] = [
  {
    id: "insignia_void_singularity",
    title: "Void Singularity",
    subtitle: "Event Horizon Crest",
    description: "Gravitational event horizon with a swirling cosmic accretion disk.",
    costSparks: 450,
    category: "cosmetic",
    type: "creator_insignia",
    value: "void-singularity",
    badge: "3-Day Vault",
    accentColor: "purple",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "insignia_synth_prime",
    title: "Synthesizer Prime",
    subtitle: "Gyroscopic Orbital Core",
    description: "Triple-ringed gyroscopic holographic orb of synthetic intelligence.",
    costSparks: 450,
    category: "cosmetic",
    type: "creator_insignia",
    value: "synth-prime",
    badge: "3-Day Vault",
    accentColor: "fuchsia",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "insignia_solar_flare",
    title: "Solar Flare",
    subtitle: "Thermonuclear Eruption",
    description: "Coronal mass eruption radiating burning thermonuclear energy.",
    costSparks: 450,
    category: "cosmetic",
    type: "creator_insignia",
    value: "solar-flare",
    badge: "3-Day Vault",
    accentColor: "amber",
    rarity: "Epic",
    rotationTier: "three_day",
  },
  {
    id: "insignia_master_architect",
    title: "Master Architect",
    subtitle: "Golden Ratio Compass",
    description: "Golden ratio precision compass drawing hyper-dimensional blueprints.",
    costSparks: 450,
    category: "cosmetic",
    type: "creator_insignia",
    value: "master-architect",
    badge: "3-Day Vault",
    accentColor: "amber",
    rarity: "Epic",
    rotationTier: "three_day",
  },
];

export const LEGENDARY_CREATOR_INSIGNIAS: SparksShopItem[] = [
  {
    id: "insignia_sovereign_crown",
    title: "Sovereign Crown",
    subtitle: "Imperial Apex Crest",
    description: "Imperial obsidian-gold crown infused with apex creator sovereignty.",
    costSparks: 750,
    category: "cosmetic",
    type: "creator_insignia",
    value: "sovereign-crown",
    badge: "Weekly Vault",
    popular: true,
    accentColor: "amber",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "insignia_paragon_hypercube",
    title: "Paragon Singularity",
    subtitle: "4D Tesseract Core",
    description: "4-dimensional hyper-tesseract bending space, light, and geometry.",
    costSparks: 750,
    category: "cosmetic",
    type: "creator_insignia",
    value: "paragon-hypercube",
    badge: "Weekly Vault",
    accentColor: "purple",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
  {
    id: "insignia_cyber_dragon",
    title: "Cyber Leviathan",
    subtitle: "Biomechanical Dragon",
    description: "Biomechanical dragon crest harboring ancient primordial reactor energy.",
    costSparks: 750,
    category: "cosmetic",
    type: "creator_insignia",
    value: "cyber-dragon",
    badge: "Weekly Vault",
    accentColor: "emerald",
    rarity: "Legendary",
    rotationTier: "weekly",
  },
];

// All cosmetics combined for lookup (Frames, Name Styles, Insignias)
export const ALL_COSMETIC_ITEMS: SparksShopItem[] = [
  ...RARE_AVATAR_FRAMES,
  ...EPIC_AVATAR_FRAMES,
  ...LEGENDARY_AVATAR_FRAMES,
  ...RARE_NAME_STYLES,
  ...EPIC_NAME_STYLES,
  ...LEGENDARY_NAME_STYLES,
  ...RARE_CREATOR_INSIGNIAS,
  ...EPIC_CREATOR_INSIGNIAS,
  ...LEGENDARY_CREATOR_INSIGNIAS,
];

// Static master array for general lookups & fallback
export const SPARKS_SHOP_ITEMS: SparksShopItem[] = [
  ...PERMANENT_SHOP_ITEMS,
  ...ALL_COSMETIC_ITEMS,
];

// ==========================================
// 5. DETERMINISTIC ROTATION ENGINE
// ==========================================

/**
 * Deterministic pseudo-random subset selection using linear congruential generator.
 * Guarantees every user sees the exact same rotation for the same time cycle.
 */
function getDeterministicSubset<T>(pool: T[], count: number, seed: number): T[] {
  if (pool.length <= count) return [...pool];
  const copy = [...pool];
  let s = Math.abs(seed) % 2147483647;
  if (s === 0) s = 12345;

  for (let i = copy.length - 1; i > 0; i--) {
    s = (s * 16807) % 2147483647;
    const j = Math.floor((s / 2147483647) * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }

  return copy.slice(0, count);
}

export interface RotationTimers {
  dailyResetUTC: Date;
  dailyCountdown: string;
  threeDayResetUTC: Date;
  threeDayCountdown: string;
  weeklyResetUTC: Date;
  weeklyCountdown: string;
}

export function formatTimeRemaining(targetDate: Date, now: Date = new Date()): string {
  const diffMs = Math.max(0, targetDate.getTime() - now.getTime());
  const totalSeconds = Math.floor(diffMs / 1000);
  const days = Math.floor(totalSeconds / 86400);
  const hours = Math.floor((totalSeconds % 86400) / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);

  if (days > 0) {
    return `${days}d ${hours}h`;
  }
  return `${hours}h ${minutes}m`;
}

/**
 * Calculates the active rotation schedules and active cosmetics for the current moment.
 */
export function getActiveCosmeticsRotation(now: Date = new Date(), cycleOffset: number = 1) {
  const nowMs = now.getTime();

  // 1. Daily Cycle (Resets at 00:00 UTC every day)
  const dayIndex = Math.floor(nowMs / 86400000) + cycleOffset;
  const nextDailyResetUTC = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + 1, 0, 0, 0, 0));
  const dailyCountdown = formatTimeRemaining(nextDailyResetUTC, now);

  // 2. 3-Day Cycle (Resets every 3 days at 00:00 UTC)
  const threeDayIndex = Math.floor(nowMs / (3 * 86400000)) + cycleOffset;
  const nextThreeDayResetUTC = new Date((threeDayIndex + 1) * 3 * 86400000);
  const threeDayCountdown = formatTimeRemaining(nextThreeDayResetUTC, now);

  // 3. Weekly Cycle (Resets every Monday at 00:00 UTC)
  const currentDayOfWeek = now.getUTCDay(); // 0 is Sunday, 1 is Monday...
  const daysUntilMonday = ((8 - currentDayOfWeek) % 7) || 7;
  const nextWeeklyResetUTC = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + daysUntilMonday, 0, 0, 0, 0));
  const weeklyCountdown = formatTimeRemaining(nextWeeklyResetUTC, now);
  const weekIndex = Math.floor((nowMs - 345600000) / (7 * 86400000)) + cycleOffset;

  // Weekly Vault (Legendary pool: 2 Frames, 2 Styles, 1 Insignia)
  const activeWeeklyFrames = getDeterministicSubset(LEGENDARY_AVATAR_FRAMES, 2, weekIndex * 13 + 7);
  const activeWeeklyGradients = getDeterministicSubset(LEGENDARY_NAME_STYLES, 2, weekIndex * 17 + 11);
  const activeWeeklyInsignias = getDeterministicSubset(LEGENDARY_CREATOR_INSIGNIAS, 1, weekIndex * 19 + 5);

  // 3-Day Vault (Epic pool: 2 Frames, 2 Styles, 1 Insignia)
  const activeThreeDayFrames = getDeterministicSubset(EPIC_AVATAR_FRAMES, 2, threeDayIndex * 23 + 5);
  const activeThreeDayGradients = getDeterministicSubset(EPIC_NAME_STYLES, 2, threeDayIndex * 29 + 13);
  const activeThreeDayInsignias = getDeterministicSubset(EPIC_CREATOR_INSIGNIAS, 1, threeDayIndex * 31 + 7);

  // Daily Drops (Rare pool: 2 Frames, 2 Styles, 1 Insignia)
  const activeDailyFrames = getDeterministicSubset(RARE_AVATAR_FRAMES, 2, dayIndex * 31 + 19);
  const activeDailyGradients = getDeterministicSubset(RARE_NAME_STYLES, 2, dayIndex * 37 + 23);
  const activeDailyInsignias = getDeterministicSubset(RARE_CREATOR_INSIGNIAS, 1, dayIndex * 43 + 13);

  const weeklyLegendaryItems = [
    ...activeWeeklyFrames,
    ...activeWeeklyGradients,
    ...activeWeeklyInsignias,
  ];

  const threeDayEpicItems = [
    ...activeThreeDayFrames,
    ...activeThreeDayGradients,
    ...activeThreeDayInsignias,
  ];

  const dailyRareItems = [
    ...activeDailyFrames,
    ...activeDailyGradients,
    ...activeDailyInsignias,
  ];

  const activeCosmetics = [
    ...weeklyLegendaryItems,
    ...threeDayEpicItems,
    ...dailyRareItems,
  ];

  const allActiveShopItems = [
    ...PERMANENT_SHOP_ITEMS,
    ...activeCosmetics,
  ];

  const timers: RotationTimers = {
    dailyResetUTC: nextDailyResetUTC,
    dailyCountdown,
    threeDayResetUTC: nextThreeDayResetUTC,
    threeDayCountdown,
    weeklyResetUTC: nextWeeklyResetUTC,
    weeklyCountdown,
  };

  return {
    timers,
    weeklyLegendaryItems,
    threeDayEpicItems,
    dailyRareItems,
    activeCosmetics,
    allActiveShopItems,
  };
}
