import { emailButton, emailDetails, emailPanel, escapeEmailHtml as escape, renderEmail } from '@/lib/email-template';
import { getServerSiteUrl } from '@/lib/site-url';
const siteUrl = getServerSiteUrl();

export function affiliateAdminEmail(data: { name: string; email: string; channel: string; audienceSize: string; message: string; ticketId: string; adminCenterLink: string }) {
  return renderEmail({ preheader: 'A new creator partnership application is ready to review.', badge: 'Partnership application', title: 'A creator wants to partner', content: emailDetails([['Applicant', data.name], ['Email', data.email], ['Channel / website', data.channel], ['Audience', data.audienceSize], ['Reference', data.ticketId]]) + emailPanel(escape(data.message || 'No additional notes.').replaceAll('\n', '<br>')) + emailButton(data.adminCenterLink, 'Review application'), footerNote: 'Internal notification for Exismic administrators.' });
}
export function affiliateApplicantEmail(data: { name: string; channel: string; audienceSize: string; ticketId: string; email: string }) {
  return renderEmail({ preheader: 'We received your Exismic creator partnership application.', badge: 'Application received', title: 'Thanks for reaching out', body: `Hi ${escape(data.name)}, your partnership application is in our review queue.`, content: emailDetails([['Channel / website', data.channel], ['Audience', data.audienceSize], ['Reference', data.ticketId], ['Email', data.email]]) + '<p>Our team will review your channel and reply with the next steps. Submission does not guarantee approval.</p>' + emailButton(`${siteUrl}/tools`, 'Explore Exismic'), footerNote: 'Questions about your application? Reply to partners@exismic.xyz.' });
}
export function supportResponseEmail(data: { name: string; replyText: string; message: string; createdAt: Date; badge: string; title: string; action: string }) {
  return renderEmail({ preheader: data.badge, badge: data.badge, title: escape(data.title), body: `Hi ${escape(data.name)},`, content: emailPanel(escape(data.replyText).replaceAll('\n', '<br>')) + '<p>You can reply directly to this email if you have questions.</p>' + (data.action === 'accept' ? emailButton(`${siteUrl}/dashboard`, 'Open your dashboard') : '') + emailPanel(`<p style="font-size:12px;">Original message · ${escape(data.createdAt.toLocaleDateString())}</p><div style="font-size:12px;color:#aab5c6;">${escape(data.message).replaceAll('\n', '<br>')}</div>`), footerNote: 'This message is a response from the Exismic team.' });
}
export function accountStatusEmail(name: string, restored: boolean) {
  return renderEmail({ preheader: restored ? 'Your Exismic account access has been restored.' : 'An update about your Exismic account access.', badge: 'Account status', title: restored ? 'Your account is restored' : 'Your account is suspended', body: `Hi ${escape(name || 'Creator')},`, content: restored ? '<p>Following a review, our team has restored your Exismic account. You can sign in to resume using your plan and credits.</p>' + emailButton(`${siteUrl}/auth/login`, 'Sign in to Exismic') : '<p>Your Exismic account has been suspended for violating our Terms of Service. Access to the dashboard and tools is restricted. If you believe this was a mistake, you can submit an appeal.</p>' + emailButton(`${siteUrl}/appeal`, 'Submit an appeal'), footerNote: restored ? 'Thank you for your patience during the review.' : 'This is an automated safety notice. Use the appeal form to request a review.' });
}
export function toolSuggestionEmail(toolName: string, description: string) {
  return renderEmail({ preheader: 'Your tool suggestion has been received.', badge: 'Tool suggestion', title: 'Thanks for your idea', body: 'Community suggestions help us decide what to build next.', content: emailDetails([['Suggested tool', toolName]]) + (description ? emailPanel(escape(description)) : '') + '<p>Our team will review your request. If we have updates or questions, we’ll contact you.</p>' + emailButton(`${siteUrl}/tools`, 'Explore the current tools'), footerNote: 'You received this email after submitting a tool suggestion on Exismic.' });
}
export function betaFeedbackEmail(data: { toolName: string; toolId: string; email: string; feedback: string; submittedAt: string }) {
  return renderEmail({ preheader: 'New feedback for the Minecraft Skin Studio.', badge: 'Beta feedback', title: 'New feedback to review', content: emailPanel(escape(data.feedback).replaceAll('\n', '<br>')) + emailDetails([['Tool', `${data.toolName} (${data.toolId})`], ['Submitted by', data.email], ['Submitted at', data.submittedAt]]), footerNote: 'Internal notification for Exismic administrators.' });
}
